import logging

# ws
WS_URL = "ws://localhost:8181"

# mysql
MYSQL_HOST = '172.18.33.200'
MYSQL_USER = 'root'
MYSQL_PASSWD = 'ruijie'
MYSQL_DB_NAME = 'ir'

# mqtt
IR_DATA_COLLECT_TOPIC = "FROM_UNVISIBLELIGHT_TOPIC"
MQTT_SERVER_IP = "192.168.10.88"
MQTT_SERVER_PORT = 1883
MQTT_KEEP_ALIVE = 60

# log
LOG_LEVEL = logging.DEBUG