import logging

# ws
WS_URL = "ws://localhost:8181"

# mysql
MYSQL_HOST = '192.168.10.133'
MYSQL_USER = 'root'
MYSQL_PASSWD = 'ruijie'
MYSQL_DB_NAME = 'ir'
MYSQL_TABLE_NAME = 'ir_data'
POOL_SIZE = 5

# mqtt
IR_DATA_COLLECT_TOPIC = "FROM_UNVISIBLELIGHT_TOPIC"
MQTT_SERVER_IP = "172.18.233.250"
MQTT_SERVER_PORT = 1883
MQTT_KEEP_ALIVE = 60

# mqtt
IS_MQTT_ONLY_COLLECT = False
MQTT_SERVER_IP_ONLY_COLLECT = "192.168.10.88"
MQTT_SERVER_PORT_ONLY_COLLECT = 1883
MQTT_KEEP_ALIVE_ONLY_COLLECT = 60

# log
LOG_LEVEL = logging.DEBUG

# data anylsis
TEMP_QUEUE_SIZE = 1000
