CREATE TABLE `ir_data` (
  `id` int NOT NULL AUTO_INCREMENT,
  `box_id` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '人员id',
  `visible_img_file_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '可见光文件路径',
  `unvisible_img_file_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '热成像文件路径',
  `tmp_img_file_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '温度图片路径',
  `vx1` int NOT NULL COMMENT '可见光vx1',
  `vx2` int NOT NULL COMMENT '可见光vx2',
  `vy1` int NOT NULL COMMENT '可见光vy1',
  `vy2` int NOT NULL COMMENT '可见光vy2',
  `x1` int NOT NULL COMMENT '热成像x1',
  `x2` int NOT NULL COMMENT '热成像x2',
  `y1` int NOT NULL COMMENT '热成像y1',
  `y2` int NOT NULL COMMENT '热成像y1',
  `evn_temp` double DEFAULT NULL COMMENT '环境温度(摄氏度)',
  `wind_speed` double DEFAULT NULL COMMENT '风速(m/s)',
  `humidity` double DEFAULT NULL COMMENT '湿度(%)',
  `lux` double DEFAULT NULL COMMENT '光照强度(lux)',
  `black_set_temp` double DEFAULT NULL COMMENT '黑体设定温度(摄氏度)',
  `black_real_temp` double DEFAULT NULL COMMENT '黑体测量温度(摄氏度)',
  `ir_temp_surf` double DEFAULT NULL COMMENT '热成像温度(摄氏度)',
  `ir_cem_surf` double DEFAULT NULL COMMENT 'cem体表温度(摄氏度)',
  `ir_o1_surf` double DEFAULT NULL COMMENT 'o1体表温度(摄氏度)',
  `ir_o2_surf` double DEFAULT NULL COMMENT 'o2体表温度(摄氏度)',
  `ir_cem_core` double DEFAULT NULL COMMENT 'cem体内温度(摄氏度)',
  `ir_o1_core` double DEFAULT NULL COMMENT 'o1体内温度(摄氏度)',
  `ir_o2_core` double DEFAULT NULL COMMENT 'o2体内温度(摄氏度)',
  `core_temp` double DEFAULT NULL COMMENT '水银体内温度(摄氏度)',
  `in_temp` double DEFAULT NULL COMMENT '机芯温度(摄氏度)',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_ir_data_box_id` (`box_id`)
) ENGINE=InnoDB AUTO_INCREMENT=13564 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;